import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  const body = await request.json().catch(() => null)
  if (!body?.input || !body?.toolName || !body?.moduleName) {
    return NextResponse.json({ error: 'Missing input, module, or tool.' }, { status: 400 })
  }

  const { moduleName, toolName, input } = body
  const apiKey = process.env.OPENAI_API_KEY || process.env.GEMINI_API_KEY

  if (!apiKey) {
    const output = `ArcUnos V3 Demo Output\n\nModule: ${moduleName}\nTool: ${toolName}\n\nYour request:\n${input}\n\nResult:\nHere is a structured professional response generated by the ArcUnos demo engine.\n\n1. Summary\n- Your request has been understood.\n- This tool is connected to the ArcUnos AI-ready workflow.\n\n2. Suggested output\n- Build the response with clear steps.\n- Keep it practical and beginner-friendly.\n- Save or export it from the workspace when needed.\n\n3. V4 upgrade note\n- When real API keys are added, this same route will call the selected AI provider instead of demo mode.\n- No UI change will be needed; only the AI service layer will become live.`
    return NextResponse.json({ output, mode: 'demo' })
  }

  // V4 hook: real provider integration will be added here.
  return NextResponse.json({
    output: `ArcUnos API key detected. V3 is intentionally running in safe demo mode. V4 will connect live AI providers here.\n\nModule: ${moduleName}\nTool: ${toolName}\nInput: ${input}`,
    mode: 'api-ready',
  })
}
